name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_module:
    name: BCR test module
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        bazel: [6.2.0, last_rc, last_green]

    steps:
      - uses: actions/checkout@v3

      - name: Test
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
        working-directory: tests
        run: |
          bazel run //:run_buildozer
          bazel test //...
